service:
  36226-ML:  # 游戏服务
    service_id: "36226-ML"
    short_code: "36226"
    keyword: "ML"
    aoc_url: "http://aoc-ic.smsgateway.cc/AIS/4208128/S2/?clickId=1{track_id}&returnURL=https%3A%2F%2Fgoogle.com"
    service_name: "GAME"
    price: "10"
    country: "TH"
    limit_sub_num: 2000
    camp_id: 2
  36881-RP:
    service_id: "36881-RP"
    short_code: "36881"
    keyword: "RP"
    aoc_url: "http://aoc-ic.smsgateway.cc/AIS/4208128/S2/?clickId=1{track_id}&returnURL=https%3A%2F%2Fgoogle.com"
    service_name: "GAME"
    price: "10"
    country: "TH"
    limit_sub_num: 2000
    camp_id: 2

